# Generated by Django 4.0.6 on 2024-02-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('suspended', 'Suspended'), ('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=255),
        ),
    ]
