# Generated by Django 4.0.6 on 2024-02-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('suspended', 'Suspended'), ('active', 'Active')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('editor', 'Editor')], max_length=255),
        ),
    ]
