# Generated by Django 5.0.2 on 2024-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=255),
        ),
    ]
