# Generated by Django 5.0.2 on 2024-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partnerprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=255),
        ),
    ]
